apiVersion: v1
kind: ConfigMap
metadata:
  name: web-html
  namespace: isol
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Hello</title>
    </head>
    <body>
      <h1>Hello, isol! </h1>
      <p>Version: 1.0.0</p>
      <p>owner : Irfath Ramiz</p>
    </body>
    </html>
