apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: isol-app-hpa
  namespace: isol
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: isol-app   
  minReplicas: 3
  maxReplicas: 10  # Maximum     replicas 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85  #CPU Percentage
