apiVersion: apps/v1
kind: Deployment
metadata:
  name: isol-app
  namespace: isol
spec:
  replicas: 3  # 0 downtime rs
  selector:
    matchLabels:
      app: isol-app
  strategy:
    type: RollingUpdate  ### Rolling restart config
    rollingUpdate:
      maxUnavailable: 0  
      maxSurge: 1  
  template:
    metadata:
      labels:
        app: isol-app
    spec:
      containers:
      - name: isol-app
        image: asia-south2-docker.pkg.dev/isol-432616/isolapp/isolapp:100.1
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db_password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db_name
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db_host
        resources:
        requests:
            cpu: "100m"  # Request 100 millicores (0.1 core)
        limits:
            cpu: "500m"  # Limit to 500 millicores (0.5 core)
